package services

import (
	"strings"
	"time"

	"github.com/medicalbilling/medical-billing-system/internal/auth"
	"github.com/medicalbilling/medical-billing-system/internal/models"
	"github.com/medicalbilling/medical-billing-system/internal/util"
	"gorm.io/gorm"
)

func now() time.Time { return time.Now() }

func (s *Services) Login(req models.LoginRequest) (*models.JwtResponse, error) {
	var user models.User
	if err := s.DB.Preload("Roles").Where("username = ?", req.Username).First(&user).Error; err != nil {
		return nil, badRequest("Invalid username or password")
	}
	if !user.Enabled || !user.AccountNonLocked {
		return nil, badRequest("Account is disabled or locked")
	}
	if !auth.CheckPassword(user.Password, req.Password) {
		return nil, badRequest("Invalid username or password")
	}
	jwt := auth.NewJWTManager("") // token generated by handler with real secret
	_ = jwt
	return &models.JwtResponse{
		Type:     "Bearer",
		ID:       user.ID,
		Username: user.Username,
		FullName: user.FullName,
		Roles:    user.RoleNames(),
	}, nil
}

func (s *Services) GetUserByUsername(username string) (*models.User, error) {
	var user models.User
	if err := s.DB.Preload("Roles").Preload("Branch").Where("username = ?", username).First(&user).Error; err != nil {
		return nil, notFound("User not found")
	}
	return &user, nil
}

func (s *Services) GetUserByID(id uint) (*models.User, error) {
	var user models.User
	if err := s.DB.Preload("Roles").First(&user, id).Error; err != nil {
		return nil, notFound("User not found")
	}
	return &user, nil
}

// Categories

func (s *Services) GetCategories(search string) ([]models.CategoryResponse, error) {
	var cats []models.Category
	q := s.DB.Order("name")
	if search != "" {
		q = q.Where("name LIKE ?", "%"+search+"%")
	}
	if err := q.Find(&cats).Error; err != nil {
		return nil, err
	}
	out := make([]models.CategoryResponse, len(cats))
	for i, c := range cats {
		out[i] = models.CategoryResponse{ID: c.ID, Name: c.Name, Description: c.Description}
	}
	return out, nil
}

func (s *Services) CreateCategory(req models.CategoryRequest, username string) (*models.CategoryResponse, error) {
	cat := models.Category{Name: req.Name, Description: req.Description, CreatedAt: now()}
	if err := s.DB.Create(&cat).Error; err != nil {
		return nil, badRequest("Category already exists or invalid")
	}
	id := cat.ID
	s.LogAudit("CREATE", "Category", &id, username, "Created category: "+cat.Name, "")
	return &models.CategoryResponse{ID: cat.ID, Name: cat.Name, Description: cat.Description}, nil
}

func (s *Services) UpdateCategory(id uint, req models.CategoryRequest, username string) (*models.CategoryResponse, error) {
	var cat models.Category
	if err := s.DB.First(&cat, id).Error; err != nil {
		return nil, notFound("Category not found")
	}
	cat.Name = req.Name
	cat.Description = req.Description
	cat.UpdatedAt = now()
	s.DB.Save(&cat)
	s.LogAudit("UPDATE", "Category", &id, username, "Updated category: "+cat.Name, "")
	return &models.CategoryResponse{ID: cat.ID, Name: cat.Name, Description: cat.Description}, nil
}

func (s *Services) DeleteCategory(id uint, username string) error {
	if err := s.DB.Delete(&models.Category{}, id).Error; err != nil {
		return notFound("Category not found")
	}
	s.LogAudit("DELETE", "Category", &id, username, "Deleted category", "")
	return nil
}

// Suppliers

func (s *Services) GetSuppliers(search string) ([]models.SupplierResponse, error) {
	var items []models.Supplier
	q := s.DB.Order("supplier_name")
	if search != "" {
		q = q.Where("supplier_name LIKE ?", "%"+search+"%")
	}
	if err := q.Find(&items).Error; err != nil {
		return nil, err
	}
	return mapSuppliers(items), nil
}

func (s *Services) GetSupplier(id uint) (*models.SupplierResponse, error) {
	var item models.Supplier
	if err := s.DB.First(&item, id).Error; err != nil {
		return nil, notFound("Supplier not found")
	}
	r := mapSuppliers([]models.Supplier{item})
	return &r[0], nil
}

func (s *Services) CreateSupplier(req models.SupplierRequest, username string) (*models.SupplierResponse, error) {
	item := models.Supplier{
		SupplierName: req.SupplierName, GSTNumber: req.GSTNumber, ContactPerson: req.ContactPerson,
		Phone: req.Phone, Email: req.Email, Address: req.Address, State: req.State, PinCode: req.PinCode,
		CreatedAt: now(),
	}
	if err := s.DB.Create(&item).Error; err != nil {
		return nil, err
	}
	id := item.ID
	s.LogAudit("CREATE", "Supplier", &id, username, "Created supplier: "+item.SupplierName, "")
	r := mapSuppliers([]models.Supplier{item})
	return &r[0], nil
}

func (s *Services) UpdateSupplier(id uint, req models.SupplierRequest, username string) (*models.SupplierResponse, error) {
	var item models.Supplier
	if err := s.DB.First(&item, id).Error; err != nil {
		return nil, notFound("Supplier not found")
	}
	item.SupplierName = req.SupplierName
	item.GSTNumber = req.GSTNumber
	item.ContactPerson = req.ContactPerson
	item.Phone = req.Phone
	item.Email = req.Email
	item.Address = req.Address
	item.State = req.State
	item.PinCode = req.PinCode
	item.UpdatedAt = now()
	s.DB.Save(&item)
	s.LogAudit("UPDATE", "Supplier", &id, username, "Updated supplier: "+item.SupplierName, "")
	r := mapSuppliers([]models.Supplier{item})
	return &r[0], nil
}

func (s *Services) DeleteSupplier(id uint, username string) error {
	if err := s.DB.Delete(&models.Supplier{}, id).Error; err != nil {
		return notFound("Supplier not found")
	}
	s.LogAudit("DELETE", "Supplier", &id, username, "Deleted supplier", "")
	return nil
}

func mapSuppliers(items []models.Supplier) []models.SupplierResponse {
	out := make([]models.SupplierResponse, len(items))
	for i, item := range items {
		out[i] = models.SupplierResponse{
			ID: item.ID, SupplierName: item.SupplierName, GSTNumber: item.GSTNumber,
			ContactPerson: item.ContactPerson, Phone: item.Phone, Email: item.Email,
			Address: item.Address, State: item.State, PinCode: item.PinCode,
			OutstandingBalance: item.OutstandingBalance,
		}
	}
	return out
}

// Customers

func (s *Services) GetCustomers(search string) ([]models.CustomerResponse, error) {
	var items []models.Customer
	q := s.DB.Order("customer_name")
	if search != "" {
		q = q.Where("customer_name LIKE ? OR phone LIKE ?", "%"+search+"%", "%"+search+"%")
	}
	if err := q.Find(&items).Error; err != nil {
		return nil, err
	}
	return mapCustomers(items), nil
}

func (s *Services) GetCustomer(id uint) (*models.Customer, error) {
	var item models.Customer
	if err := s.DB.First(&item, id).Error; err != nil {
		return nil, notFound("Customer not found")
	}
	return &item, nil
}

func (s *Services) CreateCustomer(req models.CustomerRequest, username string) (*models.CustomerResponse, error) {
	item := models.Customer{
		CustomerName: req.CustomerName, Phone: req.Phone, Email: req.Email, Address: req.Address,
		Age: req.Age, Gender: req.Gender, DoctorName: req.DoctorName, GSTNumber: req.GSTNumber,
		CreatedAt: now(),
	}
	if err := s.DB.Create(&item).Error; err != nil {
		return nil, err
	}
	id := item.ID
	s.LogAudit("CREATE", "Customer", &id, username, "Created customer: "+item.CustomerName, "")
	r := mapCustomers([]models.Customer{item})
	return &r[0], nil
}

func (s *Services) UpdateCustomer(id uint, req models.CustomerRequest, username string) (*models.CustomerResponse, error) {
	item, err := s.GetCustomer(id)
	if err != nil {
		return nil, err
	}
	item.CustomerName = req.CustomerName
	item.Phone = req.Phone
	item.Email = req.Email
	item.Address = req.Address
	item.Age = req.Age
	item.Gender = req.Gender
	item.DoctorName = req.DoctorName
	item.GSTNumber = req.GSTNumber
	item.UpdatedAt = now()
	s.DB.Save(item)
	s.LogAudit("UPDATE", "Customer", &id, username, "Updated customer: "+item.CustomerName, "")
	r := mapCustomers([]models.Customer{*item})
	return &r[0], nil
}

func (s *Services) DeleteCustomer(id uint, username string) error {
	if err := s.DB.Delete(&models.Customer{}, id).Error; err != nil {
		return notFound("Customer not found")
	}
	s.LogAudit("DELETE", "Customer", &id, username, "Deleted customer", "")
	return nil
}

func (s *Services) GetCustomerHistory(id uint) (map[string]interface{}, error) {
	if _, err := s.GetCustomer(id); err != nil {
		return nil, err
	}
	var sales []models.Sale
	s.DB.Preload("Items.Medicine").Where("customer_id = ?", id).Order("sale_date desc").Limit(20).Find(&sales)
	return map[string]interface{}{"sales": sales}, nil
}

func mapCustomers(items []models.Customer) []models.CustomerResponse {
	out := make([]models.CustomerResponse, len(items))
	for i, item := range items {
		out[i] = models.CustomerResponse{
			ID: item.ID, CustomerName: item.CustomerName, Phone: item.Phone, Email: item.Email,
			Address: item.Address, Age: item.Age, Gender: item.Gender, DoctorName: item.DoctorName,
			GSTNumber: item.GSTNumber, LoyaltyPoints: item.LoyaltyPoints,
		}
	}
	return out
}

// Medicines

func (s *Services) GetMedicines(search string) ([]models.MedicineResponse, error) {
	var items []models.Medicine
	q := s.DB.Preload("Category").Preload("Supplier").Where("status = ?", models.MedicineActive)
	if search != "" {
		q = q.Where("medicine_name LIKE ? OR medicine_code LIKE ? OR barcode LIKE ?",
			"%"+search+"%", "%"+search+"%", "%"+search+"%")
	}
	if err := q.Order("medicine_name").Find(&items).Error; err != nil {
		return nil, err
	}
	return mapMedicines(items), nil
}

func (s *Services) GetMedicine(id uint) (*models.MedicineResponse, error) {
	item, err := s.findMedicine(id)
	if err != nil {
		return nil, err
	}
	r := mapMedicines([]models.Medicine{*item})
	return &r[0], nil
}

func (s *Services) SearchMedicines(query string) ([]models.MedicineResponse, error) {
	return s.GetMedicines(query)
}

func (s *Services) GetMedicineByBarcode(barcode string) ([]models.MedicineResponse, error) {
	var items []models.Medicine
	s.DB.Preload("Category").Preload("Supplier").Where("barcode = ? AND status = ?", barcode, models.MedicineActive).Find(&items)
	return mapMedicines(items), nil
}

func (s *Services) CreateMedicine(req models.MedicineRequest, username string) (*models.MedicineResponse, error) {
	code := req.MedicineCode
	if code == "" {
		code = util.GenerateMedicineCode()
	}
	var existing int64
	s.DB.Model(&models.Medicine{}).Where("medicine_code = ?", code).Count(&existing)
	if existing > 0 {
		return nil, badRequest("Medicine code already exists")
	}
	item := s.medicineFromRequest(req)
	item.MedicineCode = code
	item.CreatedAt = now()
	if err := s.DB.Create(&item).Error; err != nil {
		return nil, err
	}
	id := item.ID
	s.DB.Preload("Category").Preload("Supplier").First(&item, item.ID)
	s.LogAudit("CREATE", "Medicine", &id, username, "Created medicine: "+item.MedicineName, "")
	r := mapMedicines([]models.Medicine{item})
	return &r[0], nil
}

func (s *Services) UpdateMedicine(id uint, req models.MedicineRequest, username string) (*models.MedicineResponse, error) {
	item, err := s.findMedicine(id)
	if err != nil {
		return nil, err
	}
	updated := s.medicineFromRequest(req)
	updated.ID = item.ID
	updated.MedicineCode = item.MedicineCode
	updated.CreatedAt = item.CreatedAt
	updated.UpdatedAt = now()
	s.DB.Save(&updated)
	s.DB.Preload("Category").Preload("Supplier").First(&updated, updated.ID)
	s.LogAudit("UPDATE", "Medicine", &id, username, "Updated medicine: "+updated.MedicineName, "")
	r := mapMedicines([]models.Medicine{updated})
	return &r[0], nil
}

func (s *Services) DeleteMedicine(id uint, username string) error {
	item, err := s.findMedicine(id)
	if err != nil {
		return err
	}
	item.Status = models.MedicineInactive
	s.DB.Save(item)
	s.LogAudit("DELETE", "Medicine", &id, username, "Deactivated medicine: "+item.MedicineName, "")
	return nil
}

func (s *Services) AdjustStock(medicineID uint, change int) error {
	return s.adjustStockDB(s.DB, medicineID, change)
}

func (s *Services) findMedicine(id uint) (*models.Medicine, error) {
	var item models.Medicine
	if err := s.DB.Preload("Category").Preload("Supplier").First(&item, id).Error; err != nil {
		return nil, notFound("Medicine not found")
	}
	return &item, nil
}

func (s *Services) medicineFromRequest(req models.MedicineRequest) models.Medicine {
	exp, _ := util.ParseDate(derefStr(req.ExpiryDate))
	mfg, _ := util.ParseDate(derefStr(req.ManufacturingDate))
	status := req.Status
	if status == "" {
		status = models.MedicineActive
	}
	return models.Medicine{
		MedicineCode: req.MedicineCode, MedicineName: req.MedicineName, CategoryID: req.CategoryID,
		Brand: req.Brand, BatchNumber: req.BatchNumber, ExpiryDate: exp, ManufacturingDate: mfg,
		HSNCode: req.HSNCode, GSTPercent: util.DerefFloat(req.GSTPercent, 0),
		PurchasePrice: req.PurchasePrice, SellingPrice: req.SellingPrice, MRP: req.MRP,
		DiscountPercent: util.DerefFloat(req.DiscountPercent, 0), RackNumber: req.RackNumber,
		MinimumStock: util.DerefInt(req.MinimumStock, 10), CurrentStock: util.DerefInt(req.CurrentStock, 0),
		Barcode: req.Barcode, SupplierID: req.SupplierID, Status: status,
	}
}

func mapMedicines(items []models.Medicine) []models.MedicineResponse {
	out := make([]models.MedicineResponse, len(items))
	for i, m := range items {
		catName, supName := "", ""
		if m.Category != nil {
			catName = m.Category.Name
		}
		if m.Supplier != nil {
			supName = m.Supplier.SupplierName
		}
		out[i] = models.MedicineResponse{
			ID: m.ID, MedicineCode: m.MedicineCode, MedicineName: m.MedicineName,
			CategoryName: catName, CategoryID: m.CategoryID, Brand: m.Brand, BatchNumber: m.BatchNumber,
			ExpiryDate: m.ExpiryDate, ManufacturingDate: m.ManufacturingDate, HSNCode: m.HSNCode,
			GSTPercent: m.GSTPercent, PurchasePrice: m.PurchasePrice, SellingPrice: m.SellingPrice,
			MRP: m.MRP, DiscountPercent: m.DiscountPercent, RackNumber: m.RackNumber,
			MinimumStock: m.MinimumStock, CurrentStock: m.CurrentStock, Barcode: m.Barcode,
			SupplierName: supName, SupplierID: m.SupplierID, Status: m.Status,
		}
	}
	return out
}

func derefStr(p *string) string {
	if p == nil {
		return ""
	}
	return *p
}

// Users

func (s *Services) GetAllUsers() ([]models.UserResponse, error) {
	var users []models.User
	if err := s.DB.Preload("Roles").Find(&users).Error; err != nil {
		return nil, err
	}
	out := make([]models.UserResponse, len(users))
	for i, u := range users {
		out[i] = toUserResponse(u)
	}
	return out, nil
}

func (s *Services) CreateUser(req models.UserRequest, adminUsername string) (*models.UserResponse, error) {
	hash, _ := auth.HashPassword(req.Password)
	var roles []models.Role
	s.DB.Where("name IN ?", req.Roles).Find(&roles)
	user := models.User{
		Username: req.Username, Password: hash, FullName: req.FullName,
		Email: req.Email, Phone: req.Phone, Roles: roles, Enabled: true, AccountNonLocked: true,
		CreatedAt: now(),
	}
	if err := s.DB.Create(&user).Error; err != nil {
		return nil, badRequest("Username already exists")
	}
	id := user.ID
	s.LogAudit("CREATE", "User", &id, adminUsername, "Created user: "+user.Username, "")
	r := toUserResponse(user)
	return &r, nil
}

func (s *Services) UpdateUser(req models.UserUpdateRequest, adminUsername string) (*models.UserResponse, error) {
	var user models.User
	if err := s.DB.Preload("Roles").First(&user, req.UserID).Error; err != nil {
		return nil, notFound("User not found")
	}
	user.Username = req.Username
	user.FullName = req.FullName
	user.Email = req.Email
	user.Phone = req.Phone
	if req.Password != "" {
		hash, _ := auth.HashPassword(req.Password)
		user.Password = hash
	}
	var roles []models.Role
	s.DB.Where("name IN ?", req.Roles).Find(&roles)
	s.DB.Model(&user).Association("Roles").Replace(roles)
	user.UpdatedAt = now()
	s.DB.Save(&user)
	id := user.ID
	s.LogAudit("UPDATE", "User", &id, adminUsername, "Updated user: "+user.Username, "")
	r := toUserResponse(user)
	return &r, nil
}

func (s *Services) DeleteUser(userID uint, adminUsername string) error {
	if err := s.DB.Delete(&models.User{}, userID).Error; err != nil {
		return notFound("User not found")
	}
	s.LogAudit("DELETE", "User", &userID, adminUsername, "Deleted user", "")
	return nil
}

func (s *Services) ResetPassword(userID uint, password, adminUsername string) error {
	var user models.User
	if err := s.DB.First(&user, userID).Error; err != nil {
		return notFound("User not found")
	}
	hash, _ := auth.HashPassword(password)
	user.Password = hash
	s.DB.Save(&user)
	s.LogAudit("UPDATE", "User", &userID, adminUsername, "Reset password for: "+user.Username, "")
	return nil
}

func (s *Services) SetUserLocked(userID uint, locked bool, adminUsername string) error {
	var user models.User
	if err := s.DB.First(&user, userID).Error; err != nil {
		return notFound("User not found")
	}
	user.AccountNonLocked = !locked
	s.DB.Save(&user)
	action := "Unlocked user"
	if locked {
		action = "Locked user"
	}
	s.LogAudit("UPDATE", "User", &userID, adminUsername, action+": "+user.Username, "")
	return nil
}

func toUserResponse(u models.User) models.UserResponse {
	return models.UserResponse{
		ID: u.ID, Username: u.Username, FullName: u.FullName, Email: u.Email, Phone: u.Phone,
		Roles: u.RoleNames(), Enabled: u.Enabled, AccountNonLocked: u.AccountNonLocked,
	}
}

func (s *Services) FindCategory(id uint) (*models.Category, error) {
	var cat models.Category
	if err := s.DB.First(&cat, id).Error; err != nil {
		return nil, notFound("Category not found")
	}
	return &cat, nil
}

func (s *Services) FindSupplier(id uint) (*models.Supplier, error) {
	var sup models.Supplier
	if err := s.DB.First(&sup, id).Error; err != nil {
		return nil, notFound("Supplier not found")
	}
	return &sup, nil
}

func (s *Services) WithTx(fn func(tx *gorm.DB) error) error {
	return s.DB.Transaction(fn)
}

func stringsContains(s, sub string) bool {
	return strings.Contains(s, sub)
}
